name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - astropy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - requests
  - future
  - json_tricks
