name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - astropy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - requests
  - future
  - astropy>=3.2
  - json_tricks
  - git://github.com/andreatramacere/oda_api.git#egg=oda_api
